# Generated by Django 5.2.7 on 2025-12-09 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_completed_at_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('courier', 'Courier'), ('pickup', 'Self-pickup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Postal code must be in the format NN-NNN.', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
