# Generated by Django 5.2.7 on 2025-12-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_bouquetflower_bouquet_and_more'),
        ('orders', '0004_alter_order_city_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flowers.bouquet'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flowers.flower'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
    ]
