# Generated by Django 5.2.7 on 2025-12-07 15:22

import django.db.models.deletion
import flowers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=flowers.models.get_flower_img_path)),
                ('in_stock', models.BooleanField(default=True)),
                ('can_be_sold_separately', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=flowers.models.get_bouquet_img_path)),
                ('categories', models.ManyToManyField(related_name='bouquets', to='flowers.bouquetcategory')),
            ],
            options={
                'verbose_name': 'Bouquet',
                'verbose_name_plural': 'Bouquets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.flower')),
            ],
            options={
                'verbose_name': 'BouquetFlower',
                'verbose_name_plural': 'BouquetFlowers',
                'ordering': ['bouquet'],
                'unique_together': {('bouquet', 'flower')},
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(related_name='bouquets', through='flowers.BouquetFlower', to='flowers.flower'),
        ),
    ]
