# Generated by Django 5.2.7 on 2025-12-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetflower',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_flowers', to='flowers.bouquet'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_flowers', to='flowers.flower'),
        ),
    ]
