# Generated by Django 5.2.7 on 2025-12-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_bouquetflower_bouquet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquetflower',
            options={'ordering': ['bouquet'], 'verbose_name': 'Bouquet Flower', 'verbose_name_plural': 'Bouquet Flowers'},
        ),
    ]
